config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks
  resources :categories
  resources :kinds
  root "bookmarks#index"

  post 'categories/:id/change' , to: 'categories#change', as: 'change'
  get 'api/categories/:id' , to: 'categories#api', as: 'api'
  get '/stats', to: 'bookmarks#stats', as: 'stats'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :title, presence: true
  validates :url, presence: true
  
  has_many :bookmark_kinds
  has_many :kinds, through: :bookmark_kinds
  accepts_nested_attributes_for :bookmark_kinds
  
  has_many :bookmark_categories
  has_many :categories, through: :bookmark_categories
  accepts_nested_attributes_for :bookmark_categories
  
  def get_categories
    formater(self.categories)
  end
 
  def get_kinds
    formater(self.kinds)
  end

  def destroy_dependant
    BookmarkCategory.where(bookmark_id: self.id).each do |x|
      x.update_attribute(:category_id, nil)
      x.delete
    end

    BookmarkKind.where(bookmark_id: self.id).each do |x|
      x.update_attribute(:kind_id, nil)
      x.delete
    end
  end

  def formater(arr)
    line = ""
    first = true
    arr.each do |obs|
      line = line + " " + obs.title
      if first
        if arr.length > 1
          line = line + ","  
        end
        first =  false
      end
    end
    line
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: %i[ show edit update destroy ]

  # GET /bookmarks or /bookmarks.json
  def index
    #Index info
    @bookmarks = Bookmark.all
    
    #Form info
    @bookmark = Bookmark.new
    
    #Category Options
    @category_options = Category.where(is_public: true)
    @kind_options = Kind.all

  end
  
  def stats
    #Graphic options
    @category_bmk = BookmarkCategory.group(:category_id).count()
    @cat_total = @category_bmk.inject(0) { |acc, (k,v)| acc+= v }
    @category_bmk = @category_bmk.map{|k,v| ["#{Category.find(k).title}: #{v} (#{percent(v,@cat_total)}%)", v] }.to_h
    
    @kind_bmk = BookmarkKind.group(:kind_id).count()
    @kind_total = @kind_bmk.inject(0) { |acc, (k,v)| acc+= v }
    @kind_bmk = @kind_bmk.map{|k,v| ["#{Kind.find(k).title}: #{v} (#{percent(v,@kind_total)}%)", v] }.to_h
  end

  # GET /bookmarks/1 or /bookmarks/1.json
  def show
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
    #Category Options
    @category_options = Category.all
    @kind_options = Kind.all

  end

  # POST /bookmarks or /bookmarks.json
  def create
    @bookmark = Bookmark.new(bookmark_params)
    respond_to do |format|
      if @bookmark.save
        @bookmarks = Bookmark.all
        @category_options = Category.all
        @kind_options = Kind.all
        format.js { render nothing: true, notice: "Bookmark was successfully created." }
        format.html { redirect_to @bookmark, notice: "Bookmark was successfully created." }
        format.json { render :show, status: :created, location: @bookmark }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1 or /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to @bookmark, notice: "Bookmark was successfully updated." }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /bookmarks/1 or /bookmarks/1.json
  def destroy
    @bookmark.destroy_dependant
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: "Bookmark was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bookmark_params
      params.require(:bookmark).permit(:title, :url, category_ids:[], kind_ids:[])
    end

    def percent(v,total)
      ((v.to_f/total.to_f)*100).round(2)
    end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_form.html.erb
<%= form_with(model: bookmark, remote: true, id:"bookmarkForm") do |form| %>
  <% if bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
        <% bookmark.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row border border-info border-2 rounded">
    <h4>New Bookmark</h4>
    <div class="col-3">
      <div class="field">
        <%= form.label :title, class: "form-label" %>
        <%= form.text_field :title, class: "form-control"%>
      </div>

      <div class="field">
        <%= form.label :url, class: "form-label" %>
        <%= form.text_field :url, class: "form-control" %>
      </div>
    </div>


    <div class="field col-4">
      <h5>Categories</h5>
      <div class="container  border border-info border-1 rounded">
        <%= form.collection_check_boxes(:category_ids, @category_options,:id,:title, class:"form-check") do |cat| %>
          <%= cat.label class: "form-check-label col-12" do %>
            <%= cat.check_box(class: "form-check-input") + cat.text  %>
          <% end %>
        <% end %>  
      </div>
    </div>

    <div class="field col-4">
      <h5>Types</h5>
      <div class="container  border border-info border-1 rounded">
        <%= form.collection_check_boxes(:kind_ids, @kind_options,:id,:title, class:"form-check") do |knd|%>
          <%= knd.label class: "form-check-label col-12" do %>
            <%= knd.check_box(class: "form-check-input") + knd.text.slice(0,1).capitalize + knd.text.slice(1..-1)  %>
          <% end %>
        <% end %>  
      </div>
    </div>
  
    <div class="row">
      <div class="actions col-2">
        <%= form.submit 'Save Bookmark', data: {confirm: 'Your confirm message'}, class: "btn btn-primary my-3"%>
      </div>
    </div>
  </div>

<% end %>

app/views/bookmarks/_index.html.erb
<% @bookmarks.each do |bookmark| %>
  <tr>
    <td><%= bookmark.title %></td>
    <td><%= bookmark.url %></td>
    <td><%= bookmark.get_categories %></td>
    <td><%= bookmark.get_kinds %></td>
    <td><%= link_to 'Show', bookmark %></td>
    <td><%= link_to 'Edit', edit_bookmark_path(bookmark) %></td>
    <td><%= link_to 'Destroy', bookmark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

app/views/bookmarks/create.js.erb
$('.form-control').val('')
$('.form-check-input').prop("checked", false);
$('#indexList').html('<%=j render "index" %>')
$('#message').html('<span>Bookmark created</span>')

app/views/bookmarks/edit.html.erb
<h1>Editing Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/index.html.erb
<p id="notice"><%= notice %></p>

<div id="message"></div>
<div id="addBookmark">
  <%= render 'form', bookmark: @bookmark %>
</div>

<h1 class="my-3">Your Bookmarks</h1>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Category</th>
      <th>Kind</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="indexList">
    <%= render 'index' %>
  </tbody>
</table>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bookmark.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @bookmark.url %>
</p>

<p>
  <strong>Categories:</strong>
  <%= @bookmark.get_categories %>
</p>

<p>
  <strong>Types:</strong>
  <%= @bookmark.get_kinds %>
</p>

<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/stats.html.erb
<h3 class="mt-4">Bookmarks distribution</h3>

<h5 class="mt-4">Category distribution</h5>
<div class="col-12 border border-info border-2 rounded row">
  <div class="col-8">
    <%= pie_chart @category_bmk%>
  </div>
  <div class="col-4">
    <table class="table">
      <thead>
        <tr>
          <th>Category</th>
          <th>Quantity</th>
        </tr>
      </thead>

      <tbody>
        <% @category_bmk.each do |k,v| %>
          <tr>
            <td><%= k %></td>
            <td><%= v %></td>
          </tr>
        <% end %>
        <tr>
          <td>Total (100%)</td>
          <td><%= @cat_total %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<h5 class="mt-4">Type distribution</h5>
<div class="col-12 border border-info border-2 rounded row">
  <div class="col-8">
    <%= pie_chart @kind_bmk%>
  </div>
  <div class="col-4">
    <table class="table">
      <thead>
        <tr>
          <th>Type</th>
          <th>Quantity</th>
        </tr>
      </thead>

      <tbody>
        <% @kind_bmk.each do |k,v| %>
          <tr>
            <td><%= k %></td>
            <td><%= v %></td>
          </tr>
        <% end %>
        <tr>
          <td>Total (100%)</td>
          <td><%= @kind_total %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>