config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks
  resources :categories
  resources :kinds
  root "bookmarks#index"

  post 'categories/:id/change' , to: 'categories#change', as: 'change'
  get 'api/categories/:id' , to: 'categories#api', as: 'api'
  get '/stats', to: 'bookmarks#stats', as: 'stats'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Bookmarks Manager</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav row">
        <div class="col-3">
            <li class="nav-item">
                <%= link_to 'Bookmarks', root_path %>
            </li>
        </div>
        <div class="col-3">
            <li class="nav-item">
                <%= link_to 'Categories', categories_path %>
            </li>
        </div>
        <div class="col-3">
            <li class="nav-item">
                <%= link_to 'Types', kinds_path %>
            </li>
        </div>
        <div class="col-3">
            <li class="nav-item">
                <%= link_to 'Statistics', stats_path %>
            </li>
        </div>
      </ul>
    </div>
  </div>
</nav>