config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks
  resources :categories
  resources :kinds
  root "bookmarks#index"

  post 'categories/:id/change' , to: 'categories#change', as: 'change'
  get 'api/categories/:id' , to: 'categories#api', as: 'api'
  get '/stats', to: 'bookmarks#stats', as: 'stats'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :category, optional: true

  validates :title, presence: true
  validates :is_public, presence: true

  has_many :bookmark_categories
  has_many :bookmarks, through: :bookmark_categories

  def get_subcategories(subcategories = [])
    subcagegories ||= []
    subcats = Category.where(category_id: self.id)
    subcats.each do |sc|
      subcategories << sc
      sc.get_subcategories(subcategories)
    end
    subcategories
  end


  def get_sc_titles()
    names = []
    self.get_subcategories.each do |x|
      names << {x.id => x.title} 
    end
    names
  end
  
  def get_bookmarks()
    bookmarks = []
    self.bookmarks.each do |x|
      bookmarks << {x.title => x.url}
    end
    bookmarks
  end
  
  #Done
  def change_public()
    self.update_attribute(:is_public, !self.is_public)
    self.get_subcategories.each do |x|
      x.update_attribute(:is_public, self.is_public)
    end
  end

  def parent
    if not self.category_id.nil?
      line = Category.find(self.category_id).title
    end
  end

  def public_status
    if self.is_public
      line = "Public"
    else
      line = "Private"
    end
  end

  def bookmark_count
    BookmarkCategory.where(category_id: self.id).count
  end

  def subcategories
    formater(self.get_subcategories)
  end

  def formater(arr)
    line = ""
    first = true
    arr.each do |obs|
      line = line + " " + obs.title
      if first
        if arr.length > 1
          line = line + ","  
        end
        first =  false
      end
    end
    line
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  before_action :set_category, only: %i[ show edit update destroy api change]
  require 'json'

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  def api 
    respuesta = {}
    respuesta[:id] = @category.id
    respuesta[:title] = @category.title
    respuesta[:subcategories] = @category.get_sc_titles
    respuesta[:bookmarks] = @category.get_bookmarks
    render json: JSON.pretty_generate(respuesta)    
  end

  # GET /categories/1 or /categories/1.json
  def show
    @bookmarks = @category.bookmarks
  end

  def change
    @category.change_public
    @categories = Category.all
    respond_to do |format|
      format.js { render nothing: true, notice: "Category Visibility was changed." }
    end
  end
  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title, :category_id, :is_public)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id %>
  </div>

  <div class="field">
    <%= form.label :is_public %>
    <%= form.check_box :is_public %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/_index.html.erb
<% @categories.each do |category| %>
  <tr>
    <td><%= category.title %></td>
    <td><%= category.parent %></td>
    <td><%= link_to category.public_status, change_path(category), method: :post, remote: :true %></td>
    <td><%= category.bookmark_count %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

app/views/categories/change.js.erb
console.log("Ejecutando")
$('#indexCategory').html('<%=j render "index" %>')
$('#message').html('<span>Visibility changed</span>')

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>
<div id="message"></div>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Parent Category</th>
      <th>Public Status</th>
      <th>Bookmarks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="indexCategory">
    <%= render 'index' %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<% if @category.is_public %>
  
<h4><%= @category.title %></h4> 
<div class="row border border-info border-2 rounded">   
  <table class="table">
    <tr>
      <th>Parent Category</th>
      <th>Public Status</th>
      <th>Sub Categories</th>
      <th>Bookmarks</th>
    
    </tr>

    <tr>
      <td><%= @category.parent %></td>
      <td><%= @category.public_status %></td>
      <td><%= @category.subcategories %></td>
      <td><%= @category.bookmark_count %></td>
    </tr>  
  </table>
  
</div>

  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Url</th>
        <th>Category</th>
        <th>Kind</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <%= render 'bookmarks/index' %>
    </tbody>
  </table>

  <%= link_to 'API', api_path(@category) %> 
  <%= link_to 'Edit', edit_category_path(@category) %> 
<% else %>
  <h4>This is a private category</h5>
  <p>that anybody can turn public... because its colaborative</p>
<% end %>
<%= link_to 'Back', categories_path %>